### ISSUE TITLE
[question] This package support video calling in mac ?

### ISSUE THREAD

**Issue by Faisalkc4u** [woodemi/Flutter-SDK-Desktop#27]

**Comment by Sunbreak** [comment]
Not yet. I'm working on it

**Comment by Sunbreak** [comment]
You could try https://github.com/flutter-webrtc/flutter-webrtc instead

**Comment by Sunbreak** [comment]
Official support here: https://github.com/AgoraIO/Agora-Flutter-SDK/issues/63#issuecomment-844975444
